name = "GamersMiddled"
author = "Gamers"
version = "1.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4cde1982d4c944a19a1f6ea538742cc8de2057410ed646c5b60ebf9a6805169"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"

[options]
no-internal-hashes = "true"
